### ISSUE TITLE
MIAN Parameter value under 0

### ISSUE THREAD

**Issue by federicoprimomo** [nickovs/kld7#1]
I get an error when I try to set the MIAN to a value under 0, example -90.
I got the error struct.error: argument out of range

**Comment by nickovs** [comment]
Thanks for the report. It looks like it probably fails for MAAN and ANTH too.  I believe the bug is in [line 234 of device.py](https://github.com/nickovs/kld7/blob/994375337139f1121da96c330b3638b898f10ce4/kld7/device.py#L234) which should have a lower-case `i` instead of an upper case `I` as the pack type.

If you have the ability to test this change to make sure that the fix works it would be most helpful, since I don't have access to a K-DL7 module at the moment.

**Comment by sandeepgaetec** [comment]
What is the transceiver chipset used in this module. Can you share the internal schematic if available with you

**Comment by ajk1982** [comment]
@nickovs I have tested the change and the fix works

**Comment by Sycamore-street** [comment]
@nickovs I also got an error while feeding (legal) negative values:
    radar.params.MIAN = -90
    radar.params.ANTH = -45
As you suggested, changing [line 234 of device.py](https://github.com/nickovs/kld7/blob/994375337139f1121da96c330b3638b898f10ce4/kld7/device.py#L234) to lower-case i instead of an upper case I, solves the problem.

> Error was:  Traceback (most recent call last):
  File "/home/projects/radar/./radarsetup.py", line 17, in <module>
    radar.params.ANTH = -45...
  File "/home/projects/radar/nickovskld7/device.py", line 234, in _send_command
    data = struct.pack(**"<I", data**)
struct.error: argument out of range

**Comment by nickovs** [comment]
Thanks for the confirmation. I will update the code and push a new version to PyPI.

**Comment by nickovs** [comment]
This is fixed by commit https://github.com/nickovs/kld7/commit/c94c83e1eddeb212367247f3c4f2b2dadddb0419 and the updated code is available as [version 0.2.1](https://pypi.org/project/kld7/0.2.1/).

**Comment by nickovs** [comment]
This is fixed by commit https://github.com/nickovs/kld7/commit/c94c83e1eddeb212367247f3c4f2b2dadddb0419 and the updated code is available as [version 0.2.1](https://pypi.org/project/kld7/0.2.1/).
